apiVersion: app/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec: 
      containers:
      - name: mongodb
        image: iamroyalreddy/mongodb:v1
      ports:
        - containerPort: 80
      