apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: app
  template:
    metadata:
      labels:
        app: mongodb
        tier: app
    spec: 
      containers:
      - name: mongodb
        image: iamroyalreddy/mongodb:v1
      ports:
        - containerPort: 80
      