apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec: 
      containers:
      - name: mongodb
        image: iamroyalreddy/mongodb:v1
---
apiVersion: v1
kind: Service
metadata:
  metadata:
    name: mongodb
    namespace: roboshop
spec:
  selector: 
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017 
      